import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import test from "node:test";

const pageSource = readFileSync(new URL("../app/page.tsx", import.meta.url), "utf8");
const globalCss = readFileSync(new URL("../app/globals.css", import.meta.url), "utf8");
const desktopSource = readFileSync(new URL("../electron/main.mjs", import.meta.url), "utf8");
const syncEngineSource = readFileSync(new URL("../electron/sync-engine.mjs", import.meta.url), "utf8");

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("renders the daily intake application", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);
  const html = await response.text();
  assert.match(html, /<title>每日摄入 · 饮食与运动记录<\/title>/i);
  assert.match(html, /每日摄入/);
  assert.match(html, /营养记录助手/);
  assert.match(html, /配置 LLM/);
  assert.match(html, /营养素总览/);
  assert.match(html, /身体趋势/);
  const clientCode = readdirSync(new URL("../dist/client/assets/", import.meta.url))
    .filter((name) => name.endsWith(".js"))
    .map((name) => readFileSync(new URL(`../dist/client/assets/${name}`, import.meta.url), "utf8"))
    .join("\n");
  assert.match(clientCode, /净摄入与运动消耗/);
  assert.match(clientCode, /蛋白质、碳水与脂肪/);
  assert.match(clientCode, /每日目标计划/);
  assert.match(clientCode, /热量缺口 \/ 盈余目标/);
  assert.match(clientCode, /遵从长期目标/);
  assert.match(clientCode, /今日特例/);
  assert.match(clientCode, /展开目标设置与详情/);
  assert.match(clientCode, /预计每月/);
  assert.match(clientCode, /参考目标/);
  assert.match(clientCode, /参考目标随历史体重与基线系数变化/);
  assert.match(clientCode, /体重趋势/);
  assert.match(clientCode, /每周平均/);
  assert.match(clientCode, /每月平均/);
  assert.match(clientCode, /导出全部记录到云盘/);
  assert.match(clientCode, /同步云端全部数据/);
  assert.match(clientCode, /已被校验快照覆盖/);
  assert.match(clientCode, /居家久坐基线/);
  assert.match(clientCode, /居家久坐基线系数/);
  assert.match(clientCode, /较低消耗 · 易胖倾向/);
  assert.match(clientCode, /较高消耗 · 易瘦倾向/);
  assert.match(clientCode, /恢复默认 1\.20/);
  assert.match(clientCode, /参考目标随历史体重与基线系数变化/);
  assert.doesNotMatch(clientCode, /浅色渐变按上下顺序分层且互不叠色/);
  assert.doesNotMatch(clientCode, /颜色之外同时使用不同线型与点形/);
  assert.match(pageSource, /macro-reference-band-\$\{band\.key\}-\$\{band\.id\}/);
  assert.match(pageSource, /MACRO_REFERENCE_MIN_FADE_PX\s*=\s*72/);
  assert.match(pageSource, /gradientUnits="userSpaceOnUse"/);
  assert.match(globalCss, /38\.4615%/);
  assert.match(globalCss, /::-webkit-slider-runnable-track/);
  assert.match(globalCss, /笔记本与高分屏可读性下限/);
  assert.match(globalCss, /\.trend-chart svg text,[\s\S]*font-size:\s*11px/);
  assert.match(clientCode, /默认 1\.20/);
  assert.doesNotMatch(pageSource, /<title>/);
  assert.match(pageSource, /SvgChartTooltip/);
  assert.match(globalCss, /\.chart-tooltip-box/);
  assert.match(globalCss, /:root\[data-theme="dark"\]/);
  assert.match(globalCss, /color-scheme:\s*dark/);
  assert.match(pageSource, /跟随系统/);
  assert.match(pageSource, /daily-intake-theme/);
  assert.match(pageSource, /<h1><span>\{displayDate\}<\/span><span>\{displayWeekday\}<\/span><\/h1>/);
  assert.match(pageSource, /<details className="target-plan-card">/);
  assert.match(pageSource, /className="target-plan-chevron"/);
  assert.match(pageSource, /<svg viewBox="0 0 20 20"/);
  assert.doesNotMatch(pageSource, /<b>⌄<\/b>/);
  assert.match(globalCss, /\.target-plan-card\[open\] \.target-plan-chevron svg \{ transform:\s*rotate\(180deg\)/);
  assert.match(pageSource, /nutrientLabels\.slice\(4\)\.map/);
  assert.doesNotMatch(pageSource, /expandedMicro/);
  assert.match(globalCss, /\.history \.analysis-panel \{ order: 1/);
  assert.match(globalCss, /\.history \.trend-controls \{ order: 2/);
  assert.match(globalCss, /\.history \.sync-panel \{ order: 7/);
  assert.match(pageSource, /function AppDatePicker/);
  assert.match(pageSource, /setPanel\("months"\)/);
  assert.match(pageSource, /setPanel\("years"\)/);
  assert.match(pageSource, /yearPageStart/);
  assert.match(pageSource, /className="calendar-choice-grid month-grid"/);
  assert.match(pageSource, /className="calendar-choice-grid year-grid"/);
  assert.doesNotMatch(pageSource, /aria-label="选择日期" type="date"/);
  assert.match(pageSource, /name="birthdate" value=\{birthdate\}/);
  assert.match(pageSource, /name="date" value=\{weightDate\}/);
  assert.doesNotMatch(pageSource, /name="birthdate" type="date"/);
  assert.match(pageSource, /originalId && originalId !== weightDate/);
  assert.match(pageSource, /dbDelete\("weights", originalId\)/);
  assert.match(pageSource, /跳过无记录日期/);
  assert.match(pageSource, /const \[weightSkipEmpty, setWeightSkipEmpty\] = useState\(false\)/);
  assert.match(pageSource, /const \[trendSkipEmpty, setTrendSkipEmpty\] = useState\(false\)/);
  assert.match(globalCss, /\.day-heading > \.app-date-picker \{[^}]*flex:\s*0 0 auto/);
  assert.match(pageSource, /createPortal\(/);
  assert.match(pageSource, /className="app-calendar app-calendar-portal"/);
  assert.match(globalCss, /\.app-calendar \{[^}]*position:\s*fixed/);
  assert.match(globalCss, /\.app-calendar \{[^}]*z-index:\s*90/);
  assert.match(pageSource, /上传本机尚未发送的新事件到云端，同时读取其他设备产生的数据，并按时间戳合并/);
  assert.match(pageSource, /立即生成包含本机当前全部未删除记录的最新备份，并选择本地保存位置/);
  assert.match(pageSource, /按记录 ID 和时间戳增量合并，不清空其他数据/);
  assert.match(pageSource, /打开备份文件夹/);
  assert.match(globalCss, /\.action-help:hover \.action-tooltip/);
  assert.doesNotMatch(globalCss, /\.backup-actions \.action-help:first-child \.action-tooltip \{[^}]*left:\s*0/);
  assert.match(globalCss, /\.backup-actions \.action-help:last-child \.action-tooltip \{[^}]*right:\s*0;[^}]*left:\s*auto/);
  assert.match(desktopSource, /\/api\/backup\/export-local/);
  assert.match(desktopSource, /showSaveDialog/);
  assert.match(desktopSource, /\/api\/backup\/import-local/);
  assert.match(desktopSource, /\/api\/sync\/open-backup-folder/);
  assert.match(globalCss, /\.trend-line\.macro-protein\.gap-segment,[\s\S]*stroke-dasharray:\s*8 6/);
  assert.match(pageSource, /function BodyDualTrendChart/);
  assert.doesNotMatch(pageSource, /function BaselineMultiplierTrendChart/);
  assert.doesNotMatch(pageSource, /className="chart-panel body-baseline-panel"/);
  assert.match(pageSource, /左轴 kg · 右轴系数/);
  assert.match(pageSource, /只有体重和系数都没有记录的日期才会被跳过/);
  assert.match(pageSource, /showWeightTrend/);
  assert.match(pageSource, /showBaselineTrend/);
  assert.match(pageSource, /const \[showWeightTrend, setShowWeightTrend\] = useState\(true\)/);
  assert.match(pageSource, /const \[showBaselineTrend, setShowBaselineTrend\] = useState\(false\)/);
  assert.match(pageSource, /selectBodyTrendDates/);
  assert.match(pageSource, /showWeight,\s*\n\s*showBaseline,\s*\n\s*skipEmpty/);
  assert.doesNotMatch(pageSource, /\[\.\.\.new Set\(\[\.\.\.weightByDate\.keys\(\), \.\.\.baselineByDate\.keys\(\)\]\)\]/);
  assert.match(globalCss, /\.body-weight-line \{[^}]*#0072b2[^}]*stroke-width:\s*3\.2/);
  assert.match(globalCss, /\.body-baseline-line \{[^}]*#e69f00[^}]*stroke-width:\s*1\.7[^}]*stroke-dasharray:\s*7 5[^}]*opacity:\s*\.55/);
  assert.match(pageSource, /gap-segment/);
  assert.match(pageSource, /trendAxisDates/);
  assert.match(pageSource, /同一天只保留一条记录/);
  assert.match(pageSource, /id:\s*weightDate,\s*date:\s*weightDate/);
  assert.match(pageSource, /全部体重记录/);
  assert.match(pageSource, /onEditWeight\(item\)/);
  assert.match(pageSource, /onDeleteWeight\(item\)/);
  assert.match(pageSource, /function DeleteWeightModal/);
  assert.match(pageSource, /删除状态会参与云盘同步/);
  assert.match(pageSource, /全部基线系数记录/);
  assert.match(pageSource, /onEditBaseline\(item\)/);
  assert.match(pageSource, /onDeleteBaseline\(item\)/);
  assert.match(pageSource, /function BaselineModal/);
  assert.match(pageSource, /function DeleteBaselineModal/);
  assert.match(pageSource, /id:\s*baselineDate,\s*\n\s*date:\s*baselineDate/);
  assert.match(pageSource, /function PaginationControls/);
  assert.match(pageSource, /function usePaginatedItems<T>\(items: T\[], initialPageSize = 10\)/);
  assert.match(pageSource, /\[10, 20, 50\]\.map/);
  assert.match(pageSource, /全部体重记录[\s\S]*weightPagination\.pageItems\.map/);
  assert.match(pageSource, /全部基线系数记录[\s\S]*baselinePagination\.pageItems\.map/);
  assert.match(pageSource, /每日汇总[\s\S]*historyPagination\.pageItems\.map/);
  assert.match(pageSource, /清除日期筛选/);
  assert.match(pageSource, /全部年份/);
  assert.match(pageSource, /跳至/);
  assert.match(globalCss, /\.pagination-bar/);
  assert.match(pageSource, /今日净摄入目标：/);
  assert.match(pageSource, /energyTargetStatus\(net, calorieTarget\)/);
  assert.match(pageSource, /--energy-status-color/);
  assert.match(globalCss, /\.energy-target-progress i \{[^}]*var\(--energy-status-color\)/);
  assert.doesNotMatch(pageSource, /calorieGap >= 0 \? "热量缺口" : "超出目标"/);
  assert.match(pageSource, /function DailyScenarioPicker/);
  assert.ok(pageSource.indexOf("<DailyScenarioPicker") < pageSource.indexOf('<section className="summary-grid">'));
  assert.match(pageSource, /name="default-target-scenario"/);
  assert.match(pageSource, /aria-label=\{`将\$\{item\.name\}设为默认`\}/);
  assert.match(pageSource, /scenario-default-toggle \$\{defaultScenario === item\.key \? "selected" : ""\}/);
  assert.match(globalCss, /\.scenario-default-toggle i::after/);
  assert.match(globalCss, /\.scenario-default-toggle input:checked \+ i::after/);
  assert.match(pageSource, /scenario-\$\{item\.key\}/);
  assert.match(globalCss, /\.daily-scenario-grid article\.scenario-strength \{[^}]*--scenario-accent:\s*#2369a5/);
  assert.match(globalCss, /\.daily-scenario-grid article\.scenario-cardio \{[^}]*--scenario-accent:\s*#327a4e/);
  assert.match(globalCss, /\.daily-scenario-grid article\.active \{[^}]*background:\s*var\(--scenario-active\)/);
  assert.match(globalCss, /\.daily-scenario-grid article\.active::before \{[^}]*z-index:\s*3[^}]*pointer-events:\s*none/);
  assert.match(globalCss, /\.daily-scenario-grid article\.active \.scenario-select::after/);
  assert.match(globalCss, /\.scenario-default-toggle\.selected \{[^}]*background:\s*var\(--scenario-default\)/);
  assert.match(globalCss, /:root\[data-theme="dark"\][\s\S]*--scenario-active:\s*#443917/);
  assert.match(globalCss, /:root\[data-theme="dark"\][\s\S]*article\.scenario-strength \{[^}]*--scenario-active:\s*#173a57/);
  assert.match(globalCss, /:root\[data-theme="dark"\][\s\S]*article\.scenario-cardio \{[^}]*--scenario-active:\s*#1d442d/);
  assert.match(pageSource, /选择卡片只修改当前显示日期/);
  assert.match(pageSource, /“设为默认”从今天起影响之后未单独设置的日期，不会改写过去/);
  assert.match(pageSource, /dbPut\("targetScenarios", record\)/);
  assert.match(pageSource, /dbPut\("targetScenarioDefaults", record\)/);
  assert.match(pageSource, /dbPut\("energyTargetDays", record\)/);
  assert.match(pageSource, /dbPut\("energyTargetDefaults", record\)/);
  assert.match(pageSource, /energyTargetForDate\(date, energyTargetDays, energyTargetDefaults\)/);
  assert.match(pageSource, /放纵日不算热量缺口/);
  assert.match(pageSource, /已存在的记录有误，需要修改：/);
  assert.match(globalCss, /\.energy-shared-slider input\[type="range"\]/);
  assert.match(globalCss, /\.energy-shared-slider\.mode-exception input\[type="range"\]::\-webkit-slider-thumb/);
  assert.match(globalCss, /\.energy-slider-scale \{[^}]*grid-template-columns:\s*1fr auto 1fr/);
  assert.match(pageSource, /的净摄入目标<\/h2>/);
  assert.match(pageSource, /className="target-plan-equation"/);
  assert.match(pageSource, /手动输入长期热量缺口或盈余/);
  assert.match(pageSource, /手动输入今日特例热量缺口或盈余/);
  assert.match(pageSource, /macroTargetsForCalories/);
  assert.match(pageSource, /energy-long-term-content \$\{selectedMode === "exception" \|\| !selectedEnabled \? "secondary" : ""\}/);
  assert.match(pageSource, /energy-target-control \$\{selectedEnabled \? "" : "target-disabled"\}/);
  assert.ok((pageSource.match(/disabled=\{!selectedEnabled\}/g) || []).length >= 5);
  assert.match(globalCss, /\.energy-long-term-content\.secondary \{[^}]*opacity:\s*\.48[^}]*grayscale/);
  assert.match(globalCss, /\.energy-target-control\.target-disabled \.energy-shared-slider \{[^}]*pointer-events:\s*none/);
  assert.match(globalCss, /\.energy-shared-slider\.mode-exception \.long-term-slider-marker/);
  assert.match(globalCss, /\.weight-projection\.warning/);
  assert.match(globalCss, /\.weight-projection\.danger/);
  assert.match(pageSource, /targetScenarioForDate\(date, targetScenarios, targetScenarioDefaults\)\.scenario/);
  assert.match(pageSource, /history-day-target/);
  assert.match(pageSource, /targetScenarioLabel\(plan\.scenario\)/);
  assert.doesNotMatch(pageSource, /className="scenario-grid"/);
  assert.match(desktopSource, /"targetScenarios", "targetScenarioDefaults"/);
  assert.match(desktopSource, /store:"targetScenarios"/);
  assert.match(desktopSource, /只有用户明确说“设为默认”“以后默认”时/);
  assert.match(desktopSource, /currentViewScenario/);
  assert.match(desktopSource, /"energyTargetDays", "energyTargetDefaults"/);
  assert.match(desktopSource, /currentViewEnergyTarget/);
  assert.match(desktopSource, /用户明确说某一天是放纵日/);
  assert.match(pageSource, /每天首次启动检查云端/);
  assert.match(pageSource, /新设备优先读取最新快照，只合并其后未覆盖的增量/);
  assert.match(syncEngineSource, /SNAPSHOT_POINTER_NAME\s*=\s*"latest\.json"/);
  assert.match(syncEngineSource, /snapshotFreshnessDays:\s*30/);
  assert.match(pageSource, /const recordedDates = filterTrendDates\(\[\.\.\.new Set\(foods\.map\(\(item\) => item\.date\)\)\]\.sort\(\), range\)/);
  assert.doesNotMatch(pageSource, /const recordedDates = filterTrendDates\(\[\.\.\.new Set\(\[\.\.\.foods\.map\([\s\S]{0,120}targetScenarios/);
  assert.match(pageSource, /dbDelete\("baselineMultipliers", originalId\)/);
  assert.match(pageSource, /dbDelete\("baselineMultipliers", record\.id\)/);
  assert.doesNotMatch(pageSource, /reverse\(\)\.slice\(0,\s*10\)/);
  assert.match(pageSource, /onMultiplierChange=\{\(multiplier\) => saveBaselineMultiplier\(date, multiplier\)\}/);
  assert.match(pageSource, /stopColor="#b7aca0"/);
  assert.match(pageSource, /type BaselineMultiplierRecord/);
  assert.match(pageSource, /baselineMultiplierForDate/);
  assert.match(pageSource, /recordedAt:\s*new Date\(\)\.toISOString\(\)/);
  assert.match(desktopSource, /"baselineMultipliers"/);
  assert.match(desktopSource, /editableExerciseRecords/);
  assert.match(desktopSource, /store:"exercises"、operation:"update"/);
  assert.match(desktopSource, /mergeEditableRecord\(records, value, store\)/);
  assert.doesNotMatch(html, /codex-preview|react-loading-skeleton/);
});
