"use client";
import { ContactDirectory } from './contact-directory';
import { useState, FormEvent, ComponentType } from 'react';
import { normalizeExerciseRecord,normalizeSex,exerciseLibraryId,walkingProfileId,walkingRate,weightForDate,sortExercises } from './exercise-library.mjs';
export type ActivityEntry={id:string;name:string;sex:string;intensity:string;note:string;caloriesPer10Minutes:number;createdAt:string;updatedAt:string};
export type WalkingProfile={id:string;sex:string;mode:'auto'|'manual';manualCaloriesPer1000:number|null;caloriesPer1000:number|null;referenceWeight:number|null;createdAt:string;updatedAt:string};
type ActivityRecord={id:string;date:string;time:string;name:string;calories:number;duration:number;steps:number;intensity:string;source:string;note:string;sex?:string;kind?:string;libraryId?:string};
type Weight={date:string;weight:number};
type PagerProps={totalItems:number;page:number;pageSize:number;totalPages:number;onPageChange:(value:number)=>void;onPageSizeChange:(value:number)=>void};
type Pager=ComponentType<PagerProps>;
const sexLabel=(sex:string)=>({male:'男',female:'女',unspecified:'未注明'}[sex]||'未注明');
const today=()=>new Date().toLocaleDateString('en-CA');
const time=()=>new Date().toTimeString().slice(0,5);
const uid=()=>crypto.randomUUID();
const format=(v:number|null|undefined)=>v==null?'待填写':Number(v).toLocaleString('zh-CN',{maximumFractionDigits:2});
const errorText=(e:unknown)=>e instanceof Error?e.message:'保存失败，请重试';
function usePage<T>(items:T[]){const [page,setPage]=useState(1),[pageSize,setPageSize]=useState(10);const totalPages=Math.max(1,Math.ceil(items.length/pageSize)),current=Math.min(page,totalPages);return {page:current,pageSize,totalPages,setPage,setPageSize,items:items.slice((current-1)*pageSize,current*pageSize)};}
function SexSelect({value,onChange}:{value:string;onChange:(v:string)=>void}){return <label>性别<select value={value} onChange={e=>onChange(e.target.value)}><option value="male">男</option><option value="female">女</option><option value="unspecified">未注明</option></select></label>;}
export function WalkingPanel({profiles,weights,sex:defaultSex,onPut}:{profiles:WalkingProfile[];weights:Weight[];sex:string;onPut:(store:string,value:object)=>Promise<void>}){
 const [sex,setSex]=useState(normalizeSex(defaultSex));
 const profile=profiles.find(x=>x.sex===sex),weight=weightForDate(weights,today());
 const [draft,setDraft]=useState<string|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const mode=profile?.mode||'auto';const effective=walkingRate(profile,weight);
 async function save(nextMode:'auto'|'manual',manual=profile?.manualCaloriesPer1000??null){setBusy(true);setError('');try{await onPut('walkingProfiles',{...profile,id:walkingProfileId(sex),sex,mode:nextMode,manualCaloriesPer1000:manual});setDraft(null);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <section className="food-library-section walking-settings">
  <div className="section-title"><div><p>步行数据库 · 每 1000 步</p><h2>步行耗能设置</h2></div><SexSelect value={sex} onChange={v=>{setSex(normalizeSex(v));setDraft(null);setError('');}} /></div>
  <div className="library-toolbar"><label>计算模式<select value={mode} disabled={busy} onChange={e=>save(e.target.value as 'auto'|'manual')}><option value="auto">自动 · 随体重更新</option><option value="manual">手动 · 固定数值</option></select></label><div className="walking-rate"><strong>{format(effective)}</strong><span> kcal / 1000 步</span></div></div>
  {mode==='auto'?<p>公式：体重 × 0.35。当前体重 {format(weight)} kg；按平地平均步长 0.7 米估算净活动耗能。修改体重会更新此费率，历史记录保持原值。</p>:<form className="library-toolbar" onSubmit={e=>{e.preventDefault();const raw=draft??(profile?.manualCaloriesPer1000==null?'':String(profile.manualCaloriesPer1000));save('manual',raw.trim()===''?null:Number(raw));}}><label>手动耗能（kcal / 1000 步）<input type="number" min="0" step="any" value={draft??(profile?.manualCaloriesPer1000??'')} onChange={e=>setDraft(e.target.value)} placeholder="留空时允许 AI 首次估算" /></label><button disabled={busy}>保存手动值</button></form>}
  {mode==='manual'&&<p>{profile?.manualCaloriesPer1000==null?'尚未设置：通过 AI 记录步行后，首次估算值会保存并锁定。':'已锁定：体重变化不会改写此值，AI 也使用此值。'} 留空保存可重新允许 AI 首次估算。</p>}
  {profile&&<div className="library-times"><span>初次记录：{new Date(profile.createdAt).toLocaleString('zh-CN')}</span><span>最近修改：{new Date(profile.updatedAt).toLocaleString('zh-CN')}</span></div>}{error&&<p role="alert">{error}</p>}
 </section>;
}
export function WalkingModal({profiles,weights,sex:initialSex,date,onClose,onSave,onPut}:{profiles:WalkingProfile[];weights:Weight[];sex:string;date:string;onClose:()=>void;onSave:(r:ActivityRecord)=>Promise<void>;onPut:(store:string,value:object)=>Promise<void>}){
 const [sex,setSex]=useState(normalizeSex(initialSex)),[recordDate,setDate]=useState(date),[steps,setSteps]=useState('1000'),[draft,setDraft]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const profile=profiles.find(x=>x.sex===sex),weight=weightForDate(weights,recordDate);const savedRate=walkingRate(profile,weight);
 const rate=savedRate??(profile?.mode==='manual'&&draft!==''?Number(draft):null);const calories=rate==null?null:rate*Number(steps)/1000;
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy||rate==null)return;const form=new FormData(e.currentTarget);setBusy(true);setError('');try{if(savedRate==null&&profile?.mode==='manual')await onPut('walkingProfiles',{...profile,sex,mode:'manual',manualCaloriesPer1000:rate});await onSave({id:uid(),date:recordDate,time:String(form.get('time')),name:'步行',kind:'walking',sex,calories:calories!,duration:0,steps:Number(steps),intensity:'日常步行',source:'步行费率',note:String(form.get('note')||'')});onClose();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <div className="modal-backdrop"><form className="modal compact" role="dialog" aria-modal="true" aria-labelledby="walking-add-title" onSubmit={submit}><div className="modal-head"><h2 id="walking-add-title">添加步行</h2><button type="button" disabled={busy} onClick={onClose}>×</button></div><div className="form-grid"><label>日期<input type="date" value={recordDate} onChange={e=>setDate(e.target.value)} required /></label><label>时间<input name="time" type="time" defaultValue={time()} required /></label><SexSelect value={sex} onChange={v=>setSex(normalizeSex(v))}/><label>步数<input autoFocus type="number" min="1" step="1" value={steps} onChange={e=>setSteps(e.target.value)} required /></label></div>
 <p>{profile?.mode==='manual'?'手动固定费率':'自动体重费率'}：{format(rate)} kcal / 1000 步</p>
 {savedRate==null&&(profile?.mode==='manual'?<label>首次手动设置（kcal / 1000 步）<input type="number" min="0" step="any" value={draft} onChange={e=>setDraft(e.target.value)} required /></label>:<p>请先记录体重，或到历史页将步行切换为手动模式。</p>)}
 <h3>本次净活动耗能：{format(calories)} kcal</h3><label>备注<input name="note" placeholder="路线或其他说明" /></label>{error&&<p role="alert">{error}</p>}<div className="modal-actions"><button type="button" disabled={busy} onClick={onClose}>取消</button><button className="primary" disabled={busy||rate==null||!Number.isFinite(calories)||Number(steps)<=0}>{busy?'保存中…':'保存步行'}</button></div></form></div>;
}
export function ActivityModal({entries,records,sex:initialSex,date,onClose,onSave}:{entries:ActivityEntry[];records:ActivityRecord[];sex:string;date:string;onClose:()=>void;onSave:(r:ActivityRecord)=>Promise<void>}){
 const [mode,setMode]=useState<'library'|'manual'>(entries.length?'library':'manual'),[sex,setSex]=useState(normalizeSex(initialSex)),[selected,setSelected]=useState(''),[duration,setDuration]=useState('10'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const items=sortExercises(entries,'','name','asc',sex) as ActivityEntry[];const picked=entries.find(x=>x.id===selected&&x.sex===sex);const calories=picked?picked.caloriesPer10Minutes*Number(duration)/10:null;
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=new FormData(e.currentTarget);if(mode==='library'&&!picked)return;setBusy(true);setError('');try{await onSave(normalizeExerciseRecord({id:uid(),date:String(form.get('date')),time:String(form.get('time')),name:mode==='library'?picked!.name:String(form.get('name')),sex,duration:Number(duration),steps:0,calories:mode==='library'?calories!:Number(form.get('calories')),intensity:mode==='library'?picked!.intensity:String(form.get('intensity')),source:mode==='library'?'运动库':String(form.get('source')),note:[mode==='library'?picked!.note:'',String(form.get('note')||'')].filter(Boolean).join('\n'),...(mode==='library'?{libraryId:picked!.id}:{})},sex));onClose();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <div className="modal-backdrop"><form className="modal directory-modal" role="dialog" aria-modal="true" aria-labelledby="activity-add-title" onSubmit={submit}><div className="modal-head"><h2 id="activity-add-title">添加运动</h2><button type="button" disabled={busy} onClick={onClose}>×</button></div><div className="library-actions activity-mode"><button type="button" aria-pressed={mode==='library'} onClick={()=>setMode('library')}>选择已记录的运动</button><button type="button" aria-pressed={mode==='manual'} onClick={()=>setMode('manual')}>手动添加</button></div><SexSelect value={sex} onChange={v=>{setSex(normalizeSex(v));setSelected('');}}/>
 {mode==='library'?<ContactDirectory onDeselect={()=>setSelected("")} key={sex} items={items} records={records} storageKey={"exercise-directory-v1-"+sex} keyOf={record=>record.libraryId||exerciseLibraryId(record.name,normalizeSex(record.sex))} selected={selected} onSelect={item=>setSelected(item.id)} summary={item=>format(item.caloriesPer10Minutes)+" kcal / 10 分钟"} busy={busy}>
 <div className="form-grid"><label>本次时长（分钟）<input type="number" min="0.1" step="any" value={duration} onChange={e=>setDuration(e.target.value)} required /></label><label>日期<input name="date" type="date" defaultValue={date} required /></label><label>时间<input name="time" type="time" defaultValue={time()} required /></label></div>{mode==='library'&&<h3>本次净活动耗能：{format(calories)} kcal</h3>}{mode==='library'&&picked?.note&&<details><summary>来源与适用说明</summary><p>{picked.note}</p></details>}<label>备注<input name="note" placeholder="次数、训练内容或估算依据；强度和配速写在名称" /></label></ContactDirectory>:<div className="directory-scroll"><label>运动名称（保留强度、配速）<input name="name" placeholder="例如：8分配跑步、中等强度健身房运动" required /></label><div className="form-grid"><label>强度<select name="intensity"><option>中等强度</option><option>较低强度</option><option>低强度</option><option>较高强度</option><option>高强度</option><option>未注明强度</option></select></label><label>本次净活动耗能（kcal）<input name="calories" type="number" min="0" step="any" required /></label><label>来源<select name="source"><option>手动填写</option><option>手表</option><option>器械</option><option>描述估算</option></select></label></div> <div className="form-grid"><label>本次时长（分钟）<input type="number" min="0.1" step="any" value={duration} onChange={e=>setDuration(e.target.value)} required /></label><label>日期<input name="date" type="date" defaultValue={date} required /></label><label>时间<input name="time" type="time" defaultValue={time()} required /></label></div><label>备注<input name="note" placeholder="次数、训练内容或估算依据；强度和配速写在名称" /></label></div>}
 {error&&<p role="alert">{error}</p>}<div className="modal-actions"><button type="button" disabled={busy} onClick={onClose}>取消</button><button className="primary" disabled={busy||(mode==='library'&&!picked)}>{busy?'保存中…':'保存运动'}</button></div></form></div>;
}
export function ActivityPanel({entries,onPut,onDelete,Pagination}:{entries:ActivityEntry[];onPut:(store:string,value:object)=>Promise<void>;onDelete:(store:string,id:string)=>Promise<void>;Pagination:Pager}){
 const [query,setQuery]=useState(''),[draft,setDraft]=useState(''),[sort,setSort]=useState('name'),[direction,setDirection]=useState('asc'),[sex,setSex]=useState('all'),[editing,setEditing]=useState<ActivityEntry|null|undefined>(undefined),[deleting,setDeleting]=useState<ActivityEntry|null>(null),[editSex,setEditSex]=useState('unspecified'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const items=sortExercises(entries,query,sort,direction,sex) as ActivityEntry[];const page=usePage(items);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=new FormData(e.currentTarget);const name=String(form.get('name'));setBusy(true);setError('');try{await onPut('exerciseLibrary',{...editing,id:editing?.id||exerciseLibraryId(name,editSex),name,sex:editSex,intensity:String(form.get('intensity')),caloriesPer10Minutes:Number(form.get('caloriesPer10Minutes')),note:String(form.get('note'))});setEditing(undefined);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 async function remove(){if(!deleting||busy)return;setBusy(true);try{await onDelete('exerciseLibrary',deleting.id);setDeleting(null);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <section className="food-library-section activity-library"><div className="section-title"><div><p>运动数据库</p><h2>每 10 分钟净活动耗能</h2></div><button onClick={()=>{setEditing(null);setEditSex('unspecified');setError('');}}>＋ 新增运动</button></div><p>强度、配速与性别分别保留。新记录按时长归一化；修改体重不会自动改写其他运动。</p><form className="library-toolbar" onSubmit={e=>{e.preventDefault();setQuery(draft);page.setPage(1);}}><label>搜索运动<input value={draft} onChange={e=>setDraft(e.target.value)}/></label><button>搜索</button><label>排序<select value={sort} onChange={e=>{setSort(e.target.value);page.setPage(1);}}><option value="name">字母 / 汉字拼音</option><option value="createdAt">初次记录时间</option><option value="updatedAt">最近修改时间</option><option value="caloriesPer10Minutes">每10分钟耗能</option></select></label><label>顺序<select value={direction} onChange={e=>{setDirection(e.target.value);page.setPage(1);}}><option value="asc">正序</option><option value="desc">倒序</option></select></label><label>性别<select value={sex} onChange={e=>{setSex(e.target.value);page.setPage(1);}}><option value="all">全部</option><option value="male">男</option><option value="female">女</option><option value="unspecified">未注明</option></select></label></form><div className="library-cards">{page.items.map(item=><article className="library-card" key={item.id}><div className="section-title"><h3>{item.name}</h3><div className="library-actions"><button onClick={()=>{setEditing(item);setEditSex(item.sex);setError('');}}>修改</button><button onClick={()=>{setDeleting(item);setError('');}}>删除</button></div></div><p><strong>{format(item.caloriesPer10Minutes)} kcal / 10 分钟</strong> · 性别：{sexLabel(item.sex)}</p><div className="library-times"><span>初次记录：{new Date(item.createdAt).toLocaleString('zh-CN')}</span><span>最近修改：{new Date(item.updatedAt).toLocaleString('zh-CN')}</span></div>{item.note&&<details><summary>备注与来源</summary><p>{item.note}</p></details>}</article>)}</div>{!items.length&&<p>暂无匹配运动。有效时长的运动记录会自动加入这里。</p>}<Pagination totalItems={items.length} page={page.page} pageSize={page.pageSize} totalPages={page.totalPages} onPageChange={page.setPage} onPageSizeChange={page.setPageSize}/>
 {editing!==undefined&&<div className="modal-backdrop"><form className="modal compact" role="dialog" aria-modal="true" onSubmit={save}><div className="modal-head"><h2>{editing?'修改':'新增'}运动库条目</h2><button type="button" disabled={busy} onClick={()=>setEditing(undefined)}>×</button></div><label>名称（保留强度、配速）<input name="name" defaultValue={editing?.name||''} required /></label><div className="form-grid"><SexSelect value={editSex} onChange={setEditSex}/><label>强度<input name="intensity" defaultValue={editing?.intensity||'中等强度'} required /></label><label>每10分钟耗能（kcal）<input name="caloriesPer10Minutes" type="number" min="0" step="any" defaultValue={editing?.caloriesPer10Minutes??''} required /></label></div><label>备注<input name="note" defaultValue={editing?.note||''}/></label>{error&&<p role="alert">{error}</p>}<div className="modal-actions"><button type="button" onClick={()=>setEditing(undefined)}>取消</button><button className="primary" disabled={busy}>保存</button></div></form></div>}
 {deleting&&<div className="modal-backdrop"><section className="modal compact" role="dialog" aria-modal="true"><h2>删除 {deleting.name}？</h2><p>历史运动记录保留，删除状态会同步到其他设备。</p>{error&&<p role="alert">{error}</p>}<div className="modal-actions"><button disabled={busy} onClick={()=>setDeleting(null)}>取消</button><button disabled={busy} onClick={remove}>确认删除</button></div></section></div>}
 </section>;
}
export function ActivityEditModal({record,onClose,onSave}:{record:ActivityRecord;onClose:()=>void;onSave:(r:ActivityRecord)=>Promise<void>}){
 const walking=normalizeExerciseRecord(record,record.sex).kind==='walking',original=walking?record.steps:record.duration;
 const [linked,setLinked]=useState(original>0),[amount,setAmount]=useState(String(original||'')),[calories,setCalories]=useState(String(record.calories)),[anchor,setAnchor]=useState({amount:original,calories:record.calories}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 function change(value:string){setAmount(value);if(linked&&anchor.amount>0)setCalories(String(anchor.calories*Number(value)/anchor.amount));}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await onSave({...record,name:String(f.get('name')),date:String(f.get('date')),time:String(f.get('time')),note:String(f.get('note')),calories:Number(calories),[walking?'steps':'duration']:Number(amount),editMode:linked?'linked':'unlinked'} as ActivityRecord);onClose();}catch(e){setError(errorText(e));setBusy(false);}}
 return <div className="modal-backdrop"><form className="modal compact" onSubmit={submit}><div className="modal-head"><h2>{walking?'修改步行':'修改运动'}</h2><button type="button" disabled={busy} onClick={onClose}>×</button></div><label>名称<input name="name" defaultValue={record.name} required readOnly={walking}/></label><div className="form-grid"><label>日期<input name="date" type="date" defaultValue={record.date} required/></label><label>时间<input name="time" type="time" defaultValue={record.time} required/></label><label>{walking?'步数':'时长（分钟）'}<input name="amount" type="number" min={walking?1:0.01} step={walking?1:'any'} value={amount} onChange={e=>change(e.target.value)} required/></label></div><div className="proportional-control"><button type="button" role="switch" aria-checked={linked} disabled={busy||(!linked&&!(Number(amount)>0))} onClick={()=>{if(!linked)setAnchor({amount:Number(amount),calories:Number(calories)});setLinked(!linked);}}>{walking?'步数':'时间'}与热量{linked?'挂钩':'脱钩'}</button><p>{linked?'按本条记录原有比例换算热量。':'可独立填写本次消耗热量。步行修改仅影响本条记录。'}</p></div><label>消耗热量（kcal）<input name="calories" type="number" min="0" step="any" required readOnly={linked} value={calories} onChange={e=>setCalories(e.target.value)}/></label><label>备注<textarea className="record-edit-note" name="note" rows={1} defaultValue={record.note}/></label>{error&&<p role="alert">{error}</p>}<div className="modal-actions"><button type="button" disabled={busy} onClick={onClose}>取消</button><button className="primary" disabled={busy}>{busy?'保存中…':'保存修改'}</button></div></form></div>;
}
