"use client";
import {useState,useEffect,ReactNode} from 'react';
import {directoryGroups} from './contact-order.mjs';
let preferenceQueue: Promise<unknown> = Promise.resolve();
const preferenceUrl=()=>new URLSearchParams(location.search).get('api');
type Entry={id:string;name:string;note?:string};
export function ContactDirectory<T extends Entry,R>({items,records,storageKey,keyOf,selected,onSelect,summary,children,onDeselect,busy=false}:{items:T[];records:R[];storageKey:string;keyOf:(r:R)=>string;selected:string;onSelect:(x:T)=>void;summary:(x:T)=>ReactNode;children:ReactNode;onDeselect:()=>void;busy?:boolean}){
 const [query,setQuery]=useState(''),[sort,setSort]=useState('alphabet'),[pins,setPins]=useState<string[]>([]),[ready,setReady]=useState(false);
 useEffect(()=>{let active=true;preferenceQueue.then(async()=>{const api=preferenceUrl();const all=api?await fetch(api+'/api/directory/preferences').then(r=>{if(!r.ok)throw Error();return r.json();}):null;const v=all?.[storageKey]??JSON.parse(localStorage.getItem(storageKey)||'{}');if(active){setSort(v.sort==='recent'?'recent':'alphabet');setPins(Array.isArray(v.pins)?v.pins.filter((x:unknown)=>typeof x==='string'):[]);setReady(true);}}).catch(()=>{if(active)setReady(true);});return()=>{active=false;};},[storageKey]);
 useEffect(()=>{if(!ready)return;const value={sort,pins};try{localStorage.setItem(storageKey,JSON.stringify(value));}catch{}const api=preferenceUrl();if(api)preferenceQueue=preferenceQueue.catch(()=>{}).then(()=>fetch(api+'/api/directory/preferences',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:storageKey,...value})}));},[sort,pins,ready,storageKey]);
 const {groups,manual,auto}=directoryGroups(items,records,pins,sort,query,keyOf);
 return <><div className="directory-toolbar"><label>搜索<input value={query} onChange={e=>{setQuery(e.target.value);onDeselect();}} placeholder="输入名称或备注" /></label><div className="directory-sort" role="group" aria-label="排列方式"><button type="button" disabled={!ready} aria-pressed={sort==='alphabet'} onClick={()=>setSort('alphabet')}>字母 / 拼音</button><button type="button" disabled={!ready} aria-pressed={sort==='recent'} onClick={()=>setSort('recent')}>最近记录</button></div></div><div className="directory-scroll">{groups.map((group:{label:string;items:T[]})=><section className="directory-group" key={group.label}><h3>{group.label}</h3>{group.items.map(item=><article className="directory-card" key={item.id} data-selected={selected===item.id}><div className="directory-row"><button className="directory-select" type="button" disabled={busy} aria-expanded={selected===item.id} onClick={()=>selected===item.id?onDeselect():onSelect(item)}><strong>{item.name}</strong><span className="directory-meta"><span>{summary(item)}</span>{auto.includes(item.id)&&<small>最近使用</small>}</span></button><button className="directory-pin" type="button" disabled={!ready||busy||(!manual.includes(item.id)&&manual.length>=5)} title={manual.length>=5&&!manual.includes(item.id)?'最多手动置顶 5 项':undefined} aria-pressed={manual.includes(item.id)} onClick={()=>setPins(manual.includes(item.id)?manual.filter((id:string)=>id!==item.id):[...manual,item.id])}>{manual.includes(item.id)?'取消置顶':'置顶'}</button></div>{selected===item.id&&<div className="directory-detail">{children}</div>}</article>)}</section>)}{!groups.length&&<p className="directory-empty">没有匹配记录</p>}</div></>;
}
