"use client";
import {useId,useMemo} from 'react';
import {recentNutrition,nutrientTrend} from './nutrient-recent.mjs';
type NutrientLabel=readonly [string,string,string];
export function RecentNutrients({foods,date,totals,recommendations,labels}:{foods:{date:string}[];date:string;totals:Record<string,number>;recommendations:Record<string,number>;labels:readonly NutrientLabel[]}){
 const prefix=useId().replace(/:/g,''),points=useMemo(()=>recentNutrition(foods,date,labels.map(x=>x[0])),[foods,date,labels]),hasCurrent=foods.some(f=>f.date===date);
 const format=(n:number)=>Number(n.toFixed(1)).toLocaleString('zh-CN');
 return <><div className="recent-nutrient-heading"><span>营养素 · 近30个记录日</span><span>当日摄入</span></div>{labels.map(([key,label,unit])=>{const target=recommendations[key],limit=key==='sodium'||key==='addedSugar',current=totals[key]||0,trend=nutrientTrend(points,key,current,target,limit,hasCurrent),id=prefix+key;return <div className="recent-nutrient-row" data-nutrient={key} data-tone={trend.tone} key={key}><div className="recent-nutrient-name"><strong>{label}</strong>{limit&&<small>建议上限</small>}</div><svg viewBox="0 0 180 64" role="img" aria-label={label+'，最近'+points.length+'个记录日；'+(hasCurrent?'当日'+format(current)+unit:'当日未记录')}><defs><linearGradient id={id+'fill'} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="currentColor" stopOpacity=".22"/><stop offset="1" stopColor="currentColor" stopOpacity="0"/></linearGradient><pattern id={id+'stripe'} width="7" height="7" patternUnits="userSpaceOnUse" patternTransform="rotate(35)"><rect width="2" height="7" fill="currentColor" opacity=".4"/></pattern><linearGradient id={id+'fade'} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="white" stopOpacity="0"/><stop offset="1" stopColor="white" stopOpacity=".8"/></linearGradient><mask id={id+'mask'}><rect x="4" y="0" width="172" height={trend.referenceY} fill={'url(#'+id+'fade)'}/></mask></defs>{limit&&target>0&&<rect className="nutrient-limit-zone" x="4" y="0" width="172" height={trend.referenceY} fill={'url(#'+id+'stripe)'} mask={'url(#'+id+'mask)'}/>}<line className="nutrient-zero-axis" x1="4" x2="176" y1={trend.zeroY} y2={trend.zeroY} strokeWidth="1"/>{target>0&&<line className="nutrient-reference-axis" x1="4" x2="176" y1={trend.referenceY} y2={trend.referenceY} stroke="currentColor" strokeDasharray="4 3" strokeWidth="1" opacity=".65"/>}{points.length>0&&<><polygon points={trend.area} fill={'url(#'+id+'fill)'}/><polyline points={trend.line} fill="none" stroke="currentColor" strokeWidth="2" strokeLinejoin="round" strokeLinecap="round"/>{trend.xy.map(([x,y]:number[],i:number)=><circle key={points[i].date} cx={x} cy={y} r={points.length===1?2.5:2} fill="currentColor"><title>{points[i].date+' · '+format(points[i][key])+unit}</title></circle>)}</>}{!points.length&&<text x="172" y="48" textAnchor="end">暂无记录</text>}</svg><div className="recent-nutrient-values"><strong>{format(current)}<small> {unit}</small></strong><span className="recent-reference">{target>0?(limit?'≤ ':'参考 ')+format(target)+' '+unit:points.length?(trend.change>0?'+':trend.change<0?'−':'')+format(Math.abs(trend.change)):'—'}</span>{!hasCurrent&&<small className="recent-no-record">当日未记录</small>}</div></div>})}<p className="recent-nutrient-period">{points.length?points[0].date+' — '+points.at(-1).date+' · '+points.length+'个记录日':'记录饮食后显示近期走势'}<br/>不足30日靠右显示；缺少记录的日期不补零。</p></>;
}
